name: Go

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:

  test:
    name: test execution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
        stable: 'false'

    - name: Test
      run: make test
      env:
        TEST_OPTIONS: -v


