name: Go

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:

  test:
    name: test execution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta1'

    - name: Test
      run: make test
      env:
        TEST_OPTIONS: '-v'

    - name: Code coverage to Coveralls
      run: |
        go get golang.org/x/tools/cmd/cover
        go install github.com/mattn/goveralls
        $HOME/gopath/bin/goveralls -service=github

